patch version

diff --git a/tests/tap-functions b/tests/tap-functions
--- a/tests/tap-functions
+++ b/tests/tap-functions
@@ -85,3 +85,15 @@ set_u=
 while getopts ":sx" opt ; do
 	case $_opt in
         u) set_u=1 ;;
+        *) usage ;;
+    esac
+done
+shift $(( OPTIND - 1 ))
+# Don't allow uninitialized variables if requested
+[[ -n "$set_u" ]] && set -u
+unset opt set_u
+
+# Used to call _cleanup on shell exit
+trap _exit EXIT
+
+
